### PR TITLE
#<01> First output: Repository setup

### PR DESCRIPTION
**Pull request by freemile2ru**
#### What does this PR do?
This PR shows the proposed output to be submitted for the **"setting up project repository checkpoint"** 

#### Description of Task to be completed?
1. Created the master branch and branched to the development branch
2. Shows how i described my commit messages following the andela style guide  
3. Created an open pull request on personal Repo and decribed it following andela style guide
4. Edited ReadMe
5. Ask fellows to comment

#### How should this be manually tested?
**N/A**

#### Any background context I want to provide?
the repository was reviewed by:

**Name: Olawale aladeusi**
Comments:
(1) basic setup checked , credit for creating a development branch and keeping the master branch clean
(2)commented on commit messages and shared the andela guide for writing commit messages
(3) suggested set the development branch as the default branch
(4) suggested i add description to my repository and the link to the hosted app when the project is complete
(5) lectured me on the appropriate times to commit my work
 
**Name: jamiu abdulmujeeb**
Comments:
(1) commended me on implementation of feedbacks gotten from Olawale
(2) suggested i add security to my master branch
(3) shared  the andela guide for naming and describing a pull request

### CODE REVIEW

**Comment by andela-uibrahim** [comment]
Name: Olawale aladeusi
Comments:
(1) basic setup checked , credit for creating a development branch and keeping the master branch clean
(2)commented on commit messages and shared the andela guide for writing commit messages
(3) suggested set the development branch as the default branch
(4) suggested i add description to my repository and the link to the hosted app when the project is complete
(5) lectured me on the appropriate times to commit my work

Name: jamiu abdulmujeeb
Comments:
(1) commended me on implementation of feedbacks gotten from Olawale
(2) suggested i add security to my master branch
(3) shared the andela guide for naming and describing a pull request

**Comment by freemile2ru** [comment]
Corrections have been implemented and two peers have been added to review this PR

**Comment by iampikuda** [comment]
Hi Usman, 

There is no title, I don't know what this pull request is about, it's way too much work to find out so make it clearer, follow the guides Bayo sent to us

PS. Next time just send me and/or whoever the link to your pull request instead of assigning us as reviewers at least that's how we've all been doing it. Let Bayo be the lone reviewer.

**Comment by freemile2ru** [comment]
hello damisi,
thank you very much for the review and the link to bayo's PR was really helpful

**Comment by freemile2ru** [comment]
hello bayo,
All corrections and reviews have been successfully implemented thank you

**Comment by q-ode** [comment]
@andela-opikuda Thanks for the contributions & pointing your team mate in the right direction!

Keep em coming!

**Review by q-ode — COMMENTED** [review]
Hey Man,

Your PR says you're "setting up project repository" but I see two outputs being worked on here which is great but does not fit what you have described.

Also, your `ReadMe` in your `Inverted Index` lacks a lot of information.

Kindly review the guidelines I send earlier.

PS: https://gist.github.com/q-ode/0b6029f7def28d3006f36d09ea6b849f

**Pull request closed without merging**
