### PR TITLE
Bayo-zanagi-rhenshaw: PR for task outputs. setup Travis CI and build on development branch, completed task automation with gulp, completed tasks for setting up linting tools.

### PR DESCRIPTION
**Pull request by rhenshaw56**
#### What does this PR do?

1) It displays the output of a task in the form of a link to a YouTube video showing auto-reloading of the browser while changes are being made to the html, css and js codes respectively.
2) It shows screenshots of Airbnb violations in the command line and hound CI comments on a PR which illustrates setting up of linters to watch for adherence to airbnb coding styles.
3) It also displays output of integrating Travis CI and a link to a passing build on my development branch

#### Description of Task to be completed?
1)A screen cast showing gulp watching and refreshing your browser when changes are made to your HTML, CSS & JS files.
2) Screenshots of Airbnb violations and HoundCI comments on a PR.
A screen 
3) [A link to a succesful travis build on development branch](https://travis-ci.org/andela-rhenshaw/inverted-index)
#### How should this be manually tested?

1)By watching the video on [YouTube](https://youtu.be/x9oTPYUQi60) 
2)By looking at the screenshots embedded here and in the output folder in the repo
3) By clicking on the link in the README.md file to checkout the Travis build

#### Any background context you want to provide?
1)Gulp is a toolkit for automating time-consuming tasks in your development workflow, so you can eliminate down-time and meet up your project deadlines. Check out [gulpjs](http://gulpjs.com/)

2)A linter is a tool that provides an API for flagging suspicious lines of written code when its syntax or logic has not met some predefined standard. The linting tool used to perform this task was eslint which is a pluggable and configurable linting tool for identifying and reporting on patterns in JavaScript.
3) [Travis CI](travis-ci.org) is a hosted distributed continuous integration service used to build and test software projects hosted at GitHub.

#### What are the relevant pivotal tracker stories?

N/A

#### Screenshots (if appropriate)
eslint-snapshot
houndci

#### Questions
N/A

### CODE REVIEW

**Review by vonvick — COMMENTED** [review]
Looks good to me

**Comment by Del-sama** [comment]
Looks good.

**Comment by q-ode** [comment]
You're making the PR to `master` kindly fix.

**Comment by iampikuda** [comment]
looks good

**Pull request closed without merging**
