### PR TITLE
Bayo izanagi aawa

### PR DESCRIPTION
**Pull request by desaawa**
#### What does this PR do?
This provides a link to the repository for the inverted index project
#### Description of Task to be completed?
Create the repository for your proposed project and at least one Pull Request
#### How should this be manually tested?
By visiting the repository link  https://github.com/andela-aawa/inverted-index
#### Any background context you want to provide?
N/A
#### Screenshots (if appropriate)
N/A
#### Questions:
N/A

### CODE REVIEW

**Review by victor-enogwe — APPROVED** [review]
Looks good

**Comment by ghost** [comment]
Good basic setup

**Review by q-ode — CHANGES_REQUESTED** [review]
Hi,

Kindly point this PR to your `bayo-izanagi-aawa-output` branch as specified.

**Comment by q-ode** [comment]
Kindly make the PR to your `-output` branch.

**Pull request closed without merging**
