### PR TITLE
chore(writing-tests): jasmine tests required for the project [Finishe…

### PR DESCRIPTION
**Pull request by hechukwu**
…s #139456297]

#### What does PR do ?

shows the link to the pull request required for the project

#### Description of Task to be completed?

a Pull Request showing all tests required for your project

#### How should this be manually tested?

to run the tests, clone the repo(thttps://github.com/andela-hchukwu/Inverted-Index), run npm install (to install dependencies) then run jasmine spec/inverted-index-test.js

#### Any background context you want to provide?
N/A

#### Questions:

N/A

#### Screenshots

N/A

### CODE REVIEW

**Comment by oreoluwade** [comment]
andela-hchukwu/Inverted-Index#13 shows the tests required but does not provide a manual demonstration of how the tests can be verified as either passing or failing. You might want to check that.

**Comment by hechukwu** [comment]
@andela-oaboluwarin I provided a background context to help verify

**Comment by iAmao** [comment]
I think your background context would be better placed in manually testing

**Comment by hechukwu** [comment]
@andela-iamao that is done, thanks.

**Comment by hechukwu** [comment]
@q-ode Kindly review this PR for merging

**Review by q-ode — COMMENTED** [review]
I've left a bunch of comments on your PR kindly address and make a resubmission.

Cheers!

**Comment by hechukwu** [comment]
Thank you

**Pull request closed without merging**
