### PR TITLE
 #<01> First output: Repository setup

### PR DESCRIPTION
**Pull request by iampikuda**
#### What does this PR do?
- It serves as my first output in checkpoint 1
 #### Description of Task to be completed?
- I setup my personal project repository
 #### How should this be manually tested?
- Check Readme file or just click [here ](https://github.com/andela-opikuda/Invertedindex/ "Visit Damisi's Project Repo")

### CODE REVIEW

**Comment by ghost** [comment]
I can see you took my feedback and added the pull request description. You could add the word Nil as the output for the other PR description headings.

**Comment by iampikuda** [comment]
Thanks. Done!

**Comment by andela-cofor** [comment]
Output requires you open a pull request...

**Comment by iampikuda** [comment]
Thanks.
Readme file updated and pull request created.

**Comment by q-ode** [comment]
Hi,

Very good attempt. I see your repo, your PR and the repo's ReadMe.

I'm however not satisfied with the answers provided to the sections in the readme plus some sections are missing.

I trust that as you get along with the project you'll improve the content as you'll gain more understanding of the application you're building.

Cheers!

**Pull request merged**
