### PR TITLE
link to my repo

### PR DESCRIPTION
**Pull request by andela-cofor**
Name: Moyosore Sosan  
Comment: Basic setup checked
Name: Raphael Akpan 
Comment: Use of naming convention to name branch, Use of temporary master branch

### CODE REVIEW

**Review by q-ode — CHANGES_REQUESTED** [review]
Hi,

Kindly rename the `Link.md` file to `README.md` as is the convention.

Please inform the rest of your team.

**Comment by andela-cofor** [comment]
Changed name from link.md to README.md

**Review by q-ode — APPROVED** [review]

**Comment by q-ode** [comment]
Hey man,

I see your repo. Great job!

However, your `ReadMe` is empty. Tells me next to nothing about what it's for and I don't see any open `Pull Requests`.

You might want to consult other fellows in simulations to see necessary sections for your `ReadMe`

**Comment by andela-cofor** [comment]
Seen, I will do that befor the end of tomorrow thank you...

**Comment by andela-cofor** [comment]
Bayo I checked out  Repos and wrote my READMe in that other, task done

**Comment by ghost** [comment]
Basic setup checked

**Comment by raphaelakpan** [comment]
Use of naming convention to name branch, Use of temporary master branch

**Comment by andela-cofor** [comment]
Bayo done all tasks given.
1. Created an open pull request on personal Repo
2. Edited ReadMe
3. Ask fellows to comment

**Comment by q-ode** [comment]
Kindly improve the `ReadeMe` of you repository according to the guidelines.

**Comment by andela-cofor** [comment]
I have edited my README based on the guidlines you sent...

**Pull request merged**
