### PR TITLE
Setting up project repository

### PR DESCRIPTION
**Pull request by eshaibu**
#### What does this PR do?

* Setup repository for project 
* Automatic browser reloading upon changes in HTML, CSS and JS files.
* Set up configurations of HoundCI and ESLint

#### Description of Task to be completed?

* Set up a repository of project and showing at least one pull request
* Browser reloads when changes are made to either the html, css or js file
*  Shows ESLint Airbnb style violations in the terminal and HoundCI comment

#### How should this be manually tested?

To see basic repository setup with updated README.md go to the link
* https://github.com/andela-eshaibu/inverted-index/tree/dev

To test browser automatic reload run the following command on your terminal
* `git clone https://github.com/andela-eshaibu/inverted-index.git`
* `cd inverted-index`
* `npm install`
* `gulp`

To test ESLint Airbnb style violations in the terminal and HoundCI comment
```
git clone https://github.com/andela-eshaibu/inverted-index.git
cd inverted-index
git checkout chore/139967463/setup-linters-dev
npm install
./node_modules/.bin/eslint testlinters.js
```
#### Any background context you want to provide?

N/A
#### What are the relevant pivotal tracker stories?

* Setting up git repository
* Automate browser reloading
* Set up ESLint and HoundCI
#### Video

* Link to browser reloading screen cast
https://www.youtube.com/watch?v=GzsqLy9x150&t=3s

#### Screenshots (if appropriate)

* Eslint Airbnb violations in terminal
eslint airbnd style violation

* HoundCI comments on PR
houndci comments
#### Questions:

N/A

### CODE REVIEW

**Comment by iAmao** [comment]
You should add at least one space after the ### in your PR description

**Comment by eshaibu** [comment]
@andela-iamao 
Okay. Done

**Comment by q-ode** [comment]
I see a lot of file changes in this PR. Most of which have nothing to do with your PR.

Kindly review and revert.

**Comment by eshaibu** [comment]
Hello Bayo,
Kindly help review this reopened PR. I have updated the PR to include the details about all file changes

**Review by q-ode — COMMENTED** [review]
I mentioned this earlier.

You didn't change most of these files.

Kindly fix your PR so the only files I see are the changes you made.

**Pull request closed without merging**
